## Pandas

In [18]:
import pandas as pd

In [19]:
'''
    --Data Analysis
    --Data Cleaning
    --Feature Engineering
    --File Handling
'''

'\n    --Data Analysis\n    --Data Cleaning\n    --Feature Engineering\n    --File Handling\n'

In [20]:
## 1D -> Series
## 2D -> DataFrame

In [21]:
numbers = pd.Series([1,2,3,4,5])
numbers

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [22]:
num = [1,2,3,4,5]
for idx, val in enumerate(num):
    print(f'{idx}    {val}')

0    1
1    2
2    3
3    4
4    5

In [23]:
emp_details = pd.DataFrame([
    ['Ram', 30, 'Bachelors', 50000, 'Backend Developer'],
    ['Hari', 30, 'Master', 30000, 'Frontend Developer'],
    ['Shyam', 30, 'Bachelors', 50000, 'Data Analyst'],
    ['Gita', 30, 'Bachelors', 20000, 'MIS Officer'],
    ['Dhiraj', 30, 'Master', 60000, 'Data Engineer'],
], columns=['Name', 'Age', 'Qualification', 'Salary', 'Job Position'],
    index = ['A', 'B', 'C', 'D', 'E'])

emp_details

     Name  Age Qualification  Salary        Job Position
A     Ram   30     Bachelors   50000   Backend Developer
B    Hari   30        Master   30000  Frontend Developer
C   Shyam   30     Bachelors   50000        Data Analyst
D    Gita   30     Bachelors   20000         MIS Officer
E  Dhiraj   30        Master   60000       Data Engineer

In [25]:
emp_details[0:3]

    Name  Age Qualification  Salary        Job Position
A    Ram   30     Bachelors   50000   Backend Developer
B   Hari   30        Master   30000  Frontend Developer
C  Shyam   30     Bachelors   50000        Data Analyst

In [27]:
emp_details['A': 'C']

    Name  Age Qualification  Salary        Job Position
A    Ram   30     Bachelors   50000   Backend Developer
B   Hari   30        Master   30000  Frontend Developer
C  Shyam   30     Bachelors   50000        Data Analyst

## loc and iloc

In [29]:
"""
-loc -> location -> Slice data through alphabetical order
-iloc -> Integer Location -> Slice data through numerical index
"""

'\n-loc -> location -> Slice data through alphabetical order\n-iloc -> Integer Location -> Slice data through numerical index\n'

In [30]:
emp_details.iloc[0:3, 1:4]

   Age Qualification  Salary
A   30     Bachelors   50000
B   30        Master   30000
C   30     Bachelors   50000

In [31]:
emp_details.loc['A':'D', 'Age':'Salary']

   Age Qualification  Salary
A   30     Bachelors   50000
B   30        Master   30000
C   30     Bachelors   50000
D   30     Bachelors   20000

In [32]:
emp_details.iloc[
    [1,4],
    [0,4]
]

     Name        Job Position
B    Hari  Frontend Developer
E  Dhiraj       Data Engineer

In [33]:
emp_details.loc[
    ['B', 'E'],
    ['Name', 'Job Position']
]

     Name        Job Position
B    Hari  Frontend Developer
E  Dhiraj       Data Engineer

In [34]:
emp_details.shape

(5, 5)

In [35]:
emp_details.size

25

In [36]:
len(emp_details)

5

In [37]:
emp_details.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A to E
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           5 non-null      object
 1   Age            5 non-null      int64
 2   Qualification  5 non-null      object
 3   Salary         5 non-null      int64
 4   Job Position   5 non-null      object
dtypes: int64(2), object(3)
memory usage: 412.0+ bytes