In [16]:
'''
- csv -> read_csv()
- excel -> read_excel()
    -> No module found openpyxl. -> pip install openpyxl
- sql -> read_sql()
- json -> read_json()
'''

'\n- csv -> read_csv()\n- excel -> read_excel()\n    -> No module found openpyxl. -> pip install openpyxl\n- sql -> read_sql()\n- json -> read_json()\n'

In [17]:
import pandas as pd

In [18]:
df = pd.read_csv('Dataset/Employees.csv')
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [19]:
df.tail()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    object
 2   LAST_NAME       111 non-null    object
 3   EMAIL           111 non-null    object
 4   PHONE_NUMBER    111 non-null    object
 5   HIRE_DATE       111 non-null    object
 6   JOB_ID          111 non-null    object
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  35 non-null     float64
 9   MANAGER_ID      110 non-null    float64
 10  DEPARTMENT_ID   110 non-null    float64
dtypes: float64(3), int64(2), object(6)
memory usage: 9.7+ KB

In [ ]:

''' 
2. What are the types of data?

    1. Numeric Data
    a. Discrete
        - Countable whole numbers.
        - Examples: Number of students, Number of cars, Employee ID (although IDs are often treated as categorical labels)

    b. Continuous
        - Can take any value within a range.
        - Examples: Temperature, Height, Weight, Salary, Price, Time

    2. Categorical Data
    a. Nominal
        - Categories with no natural order or ranking.
        - Examples: Gender, Color, Blood Group, Country, Caste

    b. Ordinal
        - Categories with a meaningful order or ranking.
        - Examples: Grade (A, B, C), Education Level, Satisfaction (Low, Medium, High), Qualification
'''

' \n2. What are the types of data?\n\n    1. Numeric Data\n    a. Discrete\n        - Countable whole numbers.\n        - Examples: Number of students, Number of cars, Employee ID (although IDs are often treated as categorical labels)\n\n    b. Continuous\n        - Can take any value within a range.\n        - Examples: Temperature, Height, Weight, Salary, Price, Time\n\n    2. Categorical Data\n    a. Nominal\n        - Categories with no natural order or ranking.\n        - Examples: Gender, Color, Blood Group, Country, Caste\n\n    b. Ordinal\n        - Categories with a meaningful order or ranking.\n        - Examples: Grade (A, B, C), Education Level, Satisfaction (Low, Medium, High), Qualification\n'

In [26]:
emp_sal = df[df['SALARY']>15000]
emp_sal

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0