In [61]:
import numpy as np
import pandas as pd

In [62]:
df = pd.read_csv("Dataset/Employees.csv")
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

In [63]:
emp_sal = df['SALARY']>15000
emp_sal

0       True
1       True
2       True
3      False
4      False
       ...
106    False
107    False
108    False
109    False
110    False
Name: SALARY, Length: 111, dtype: bool

In [64]:
emp_sal = df[df['SALARY']>15000]
emp_sal

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0

In [65]:
emp_sal = df.where(df['SALARY'] > 15000).dropna(how='all')
emp_sal

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100.0,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000.0,NaN,NaN,90.0
1,101.0,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000.0,NaN,100.0,90.0
2,102.0,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000.0,NaN,100.0,90.0

In [66]:
df['Status'] = np.where(df['SALARY'] > 15000, 'High', 'Low')
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,Status
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0,High
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0,High
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0,High
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0,Low
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0,Low

In [67]:
emp_salary = df[(df['SALARY'] >= 10000) & (df['SALARY'] < 18000)]
emp_salary[['EMPLOYEE_ID', 'FIRST_NAME', 'LAST_NAME', 'SALARY']].head()

    EMPLOYEE_ID FIRST_NAME  LAST_NAME  SALARY
1           101      Neena    Kochhar   17000
2           102        Lex    De Haan   17000
8           108      Nancy  Greenberg   12008
14          114        Den   Raphaely   11000
45          145       John    Russell   14000

In [68]:
emp_salary_between = df[df['SALARY'].between(10000,18000)] # between is inclusive
emp_salary_between.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,Status
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0,High
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0,High
8,108,Nancy,Greenberg,NGREENBE,515.124.4569,8/17/2002,FI_MGR,12008,NaN,101.0,100.0,Low
14,114,Den,Raphaely,DRAPHEAL,515.127.4561,12/7/2002,PU_MAN,11000,NaN,100.0,30.0,Low
45,145,John,Russell,JRUSSEL,011.44.1344.429268,10/1/2004,SA_MAN,14000,0.4,100.0,80.0,Low

In [69]:
## Find employees details who work in job AD_VP and IT_PROG.
emp_filter = df[(df['JOB_ID']=='AD_VP') | (df['JOB_ID'] == "IT_PROG")]
emp_filter.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,Status
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0,High
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0,High
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0,Low
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0,Low
5,105,David,Austin,DAUSTIN,590.423.4569,6/25/2005,IT_PROG,4800,NaN,103.0,60.0,Low

In [70]:
emp_job_in = df[df['JOB_ID'].isin(['AD_VP','IT_PROG'])]
emp_job_in

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,Status
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0,High
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0,High
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0,Low
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0,Low
5,105,David,Austin,DAUSTIN,590.423.4569,6/25/2005,IT_PROG,4800,NaN,103.0,60.0,Low
6,106,Valli,Pataballa,VPATABAL,590.423.4560,2/5/2006,IT_PROG,4800,NaN,103.0,60.0,Low
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,2/7/2007,IT_PROG,4200,NaN,103.0,60.0,Low

In [71]:
job_list = [
    'AD_VP',
    'IT_PROG'
]
emp_job_in = df[df['JOB_ID'].isin(job_list)]
emp_job_in.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,Status
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0,High
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0,High
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0,Low
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0,Low
5,105,David,Austin,DAUSTIN,590.423.4569,6/25/2005,IT_PROG,4800,NaN,103.0,60.0,Low

In [72]:
emp_detail = df[(df['SALARY'] > 8000) & ((df['DEPARTMENT_ID'] == 60) | (df['DEPARTMENT_ID'] == 70))]
emp_detail

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,Status
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0,Low
104,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0,Low
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0,Low

In [73]:
new_df = pd.read_csv("Dataset/HR_Dataset Refresh.csv")
new_df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

In [74]:
# filter single boolean condition
filter = new_df[new_df['Department'] == 'IT/IS']
filter[['Department', 'EmpID', 'Employee_Name']].head()

   Department  EmpID             Employee_Name
1       IT/IS  10084  Ait Sidi, Karthikeyan
9       IT/IS  10250        Bacong, Alejandro
12      IT/IS  10012          Barbossa, Hector
18      IT/IS  10245             Becker, Renee
20      IT/IS  10084  Ait Sidi, Karthikeyan

In [77]:
# multi-condition filtering using and (&)
new_df['Department'] = new_df['Department'].str.strip()
filter = new_df[(new_df['Department'] == 'Production') & (new_df['EmpSatisfaction'] < 3)]
filter[['Department','EmpSatisfaction']].head(5)

     Department  EmpSatisfaction
73   Production                2
88   Production                2
102  Production                1
156  Production                2
207  Production                2

In [ ]:
## multi-condition filtering using or(|)
filter = new_df[new_df['RecruitmentSource'].isin(['Glassdoor','Employee Referral'])]
filter.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
7,"Athwal, Sam",10062,0,4,1,1,5,3,0,59365,...,Ketsia Liebig,19.0,Employee Referral,Fully Meets,5.00,4,0,2/25/2019,0,19
16,"Beak, Kimberly",10023,1,1,0,2,5,4,0,70131,...,Kelley Spirea,18.0,Employee Referral,Exceeds,4.40,3,0,1/14/2019,0,16
26,"Athwal, Sam",10062,0,4,1,1,5,3,0,59365,...,Ketsia Liebig,19.0,Employee Referral,Fully Meets,5.00,4,0,2/25/2019,0,19
35,"Beak, Kimberly",10023,1,1,0,2,5,4,0,70131,...,Kelley Spirea,18.0,Employee Referral,Exceeds,4.40,3,0,1/14/2019,0,16
52,"Burke, Joelle",10107,0,0,0,1,5,3,0,63763,...,Amy Dunn,11.0,Employee Referral,Fully Meets,4.51,4,0,2/21/2019,0,3

In [78]:
# numeric ranges and column slicing
filter = new_df[(new_df['Salary'] > 100000) & (new_df['Absences'] > 10)]
filter[['Employee_Name','Position','ManagerName']].head()

                Employee_Name                Position      ManagerName
1    Ait Sidi, Karthikeyan                    Sr. DBA       Simon Roup
20   Ait Sidi, Karthikeyan                    Sr. DBA       Simon Roup
74             Corleone, Vito  Director of Operations       Janet King
115               Foss, Jason             IT Director  Jennifer Zamora
150           Houlihan, Debra       Director of Sales       Janet King

In [79]:
emp_mgr = new_df[(new_df['ManagerName'] == 'Kissy Sullivan') & (new_df['DaysLateLast30'] > 0)]
emp_mgr.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
72,"Cole, Spencer",10292,0,0,1,4,5,2,0,59144,...,Kissy Sullivan,20.0,LinkedIn,Needs Improvement,2.00,3,0,5/1/2016,5,16
224,"O'hare, Lynn",10303,0,0,0,4,5,1,0,52674,...,Kissy Sullivan,20.0,LinkedIn,PIP,2.33,2,0,3/9/2018,6,3