In [1]:
'''
- Data Wrangling
    - Data Cleaning
        - Fill Null Values:
            - fillna() : used to fill null values.
                        -> if continues Record fill using:
                            mean - if values are in range 
                            median - if values are not in range
                        -> if discrete/categorical fill using:
                            mode, custom record: 0/assume

            - Skewness
            - 0 or near zero -> fill data with mean value
            - if value is less than 0 and equals to or 
              more than 0.5 then fill median value

        - Drop Columns/Rows
            -dropna()
                -> axis -> 0(Row)
                -> axis -> 1(Column)

        - Remove Duplicate Records
            - always do this at first
            - to find duplicate values -> duplicated()
            - to drop duplicate values -> drop_duplicates()

        - Remove unwanted data (special characters / Regular Expressions)
            - str.replace()

        - Removing Whitespaces
            - str.strip() -> remove both side whitespace
            - str.lstrip() -> remove left side whitespace
            - str.rstrip() -> remove right side whitespace

        imp: stats - Mean, Median, Mode, Skewness, Kurtosis, std, variance

    - Feature Engineering


    Average
    -------------
    =Average(Range)
    
    Median
    ---------------
    =Median(Range)
    
    Skewness
    --------------------
    =Skew(Range)
    
    Count Values
    ----------------------
    =countif(range, value)


'''

'\n- Data Wrangling\n    - Data Cleaning\n        - Fill Null Values:\n            - fillna() : used to fill null values.\n                        -> if continues Record fill using:\n                            mean - if values are in range \n                            median - if values are not in range\n                        -> if discrete/categorical fill using:\n                            mode, custom record: 0/assume\n\n            - Skewness\n            - 0 or near zero -> fill data with mean value\n            - if value is less than 0 and equals to or \n              more than 0.5 then fill median value\n\n        - Drop Columns/Rows\n            -dropna()\n                -> axis -> 0(Row)\n                -> axis -> 1(Column)\n\n        - Remove Duplicate Records\n            - always do this at first\n            - to find duplicate values -> duplicated()\n            - to drop duplicate values -> drop_duplicates()\n\n        - Remove unwanted data (special characters / Regular Expressions)\n            - str.replace()\n\n        - Removing Whitespaces\n            - str.strip() -> remove both side whitespace\n            - str.lstrip() -> remove left side whitespace\n            - str.rstrip() -> remove right side whitespace\n\n        imp: stats - Mean, Median, Mode, Skewness, Kurtosis, std, variance\n\n    - Feature Engineering\n\n\n    Average\n    -------------\n    =Average(Range)\n    \n    Median\n    ---------------\n    =Median(Range)\n    \n    Skewness\n    --------------------\n    =Skew(Range)\n    \n    Count Values\n    ----------------------\n    =countif(range, value)\n\n\n'

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Dataset/Employees.csv')
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    object
 2   LAST_NAME       111 non-null    object
 3   EMAIL           111 non-null    object
 4   PHONE_NUMBER    111 non-null    object
 5   HIRE_DATE       111 non-null    object
 6   JOB_ID          111 non-null    object
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  35 non-null     float64
 9   MANAGER_ID      110 non-null    float64
 10  DEPARTMENT_ID   110 non-null    float64
dtypes: float64(3), int64(2), object(6)
memory usage: 9.7+ KB

In [5]:
# to check null values
df.isnull().sum()

EMPLOYEE_ID        0
FIRST_NAME         0
LAST_NAME          0
EMAIL              0
PHONE_NUMBER       0
HIRE_DATE          0
JOB_ID             0
SALARY             0
COMMISSION_PCT    76
MANAGER_ID         1
DEPARTMENT_ID      1
dtype: int64

In [6]:
'''
To change data permanently
------------------------------
1. inplace = True / False (default)
'''

'''
dropna()
-------------
dropna(
    axis=0(default)/1, 
    how='any'(default)/'all', 
    inplace=True/False(default)
)
'''

"\ndropna()\n-------------\ndropna(\n    axis=0(default)/1, \n    how='any'(default)/'all', \n    inplace=True/False(default)\n)\n"

In [7]:
# to drop values
# df.dropna(axis=0, how='any', inplace=True)

In [8]:
# df = df.dropna()

In [9]:
'''
to drop specific columns
--------------------------
drop(columns=[column_name])
'''

'\nto drop specific columns\n--------------------------\ndrop(columns=[column_name])\n'

In [10]:
df = df.drop(columns='EMAIL')
# df = df.drop(columns=['SALARY', 'JOB_ID'])
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0