In [1]:
'''
- Data Wrangling
    - Data Cleaning
        - Fill Null Values:
            - fillna() : used to fill null values.
                        -> if continues Record fill using:
                            mean - if values are in range 
                            median - if values are not in range
                        -> if discrete/categorical fill using:
                            mode, custom record: 0/assume

            - Skewness
            - 0 or near zero -> fill data with mean value
            - if value is less than 0 and equals to or 
              more than 0.5 then fill median value

        - Drop Columns/Rows
            -dropna()
                -> axis -> 0(Row)
                -> axis -> 1(Column)

        - Remove Duplicate Records
            - always do this at first
            - to find duplicate values -> duplicated()
            - to drop duplicate values -> drop_duplicates()

        - Remove unwanted data (special characters / Regular Expressions)
            - str.replace()

        - Removing Whitespaces
            - str.strip() -> remove both side whitespace
            - str.lstrip() -> remove left side whitespace
            - str.rstrip() -> remove right side whitespace

        imp: stats - Mean, Median, Mode, Skewness, Kurtosis, std, variance

    - Feature Engineering


    Average
    -------------
    =Average(Range)
    
    Median
    ---------------
    =Median(Range)
    
    Skewness
    --------------------
    =Skew(Range)
    
    Count Values
    ----------------------
    =countif(range, value)


- Change Data Types:
    -> astype()

'''

'\n- Data Wrangling\n    - Data Cleaning\n        - Fill Null Values:\n            - fillna() : used to fill null values.\n                        -> if continues Record fill using:\n                            mean - if values are in range \n                            median - if values are not in range\n                        -> if discrete/categorical fill using:\n                            mode, custom record: 0/assume\n\n            - Skewness\n            - 0 or near zero -> fill data with mean value\n            - if value is less than 0 and equals to or \n              more than 0.5 then fill median value\n\n        - Drop Columns/Rows\n            -dropna()\n                -> axis -> 0(Row)\n                -> axis -> 1(Column)\n\n        - Remove Duplicate Records\n            - always do this at first\n            - to find duplicate values -> duplicated()\n            - to drop duplicate values -> drop_duplicates()\n\n        - Remove unwanted data (special characters / Regular Expressions)\n            - str.replace()\n\n        - Removing Whitespaces\n            - str.strip() -> remove both side whitespace\n            - str.lstrip() -> remove left side whitespace\n            - str.rstrip() -> remove right side whitespace\n\n        imp: stats - Mean, Median, Mode, Skewness, Kurtosis, std, variance\n\n    - Feature Engineering\n\n\n    Average\n    -------------\n    =Average(Range)\n    \n    Median\n    ---------------\n    =Median(Range)\n    \n    Skewness\n    --------------------\n    =Skew(Range)\n    \n    Count Values\n    ----------------------\n    =countif(range, value)\n\n\n- Change Data Types:\n    -> astype()\n\n'

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Dataset/Employees.csv')
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    object
 2   LAST_NAME       111 non-null    object
 3   EMAIL           111 non-null    object
 4   PHONE_NUMBER    111 non-null    object
 5   HIRE_DATE       111 non-null    object
 6   JOB_ID          111 non-null    object
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  35 non-null     float64
 9   MANAGER_ID      110 non-null    float64
 10  DEPARTMENT_ID   110 non-null    float64
dtypes: float64(3), int64(2), object(6)
memory usage: 9.7+ KB

In [5]:
# to check null values
df.isnull().sum()

EMPLOYEE_ID        0
FIRST_NAME         0
LAST_NAME          0
EMAIL              0
PHONE_NUMBER       0
HIRE_DATE          0
JOB_ID             0
SALARY             0
COMMISSION_PCT    76
MANAGER_ID         1
DEPARTMENT_ID      1
dtype: int64

In [6]:
'''
To change data permanently
------------------------------
1. inplace = True / False (default)
'''

'''
dropna()
-------------
dropna(
    axis=0(default)/1, 
    how='any'(default)/'all', 
    inplace=True/False(default)
)
'''

"\ndropna()\n-------------\ndropna(\n    axis=0(default)/1, \n    how='any'(default)/'all', \n    inplace=True/False(default)\n)\n"

In [7]:
# to drop values
# df.dropna(axis=0, how='any', inplace=True)

In [8]:
# df = df.dropna()

In [9]:
'''
to drop specific columns
--------------------------
drop(columns=[column_name])
'''

'\nto drop specific columns\n--------------------------\ndrop(columns=[column_name])\n'

In [10]:
df = df.drop(columns='EMAIL')
# df = df.drop(columns=['SALARY', 'JOB_ID'])
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

##  Fill Data

In [11]:
df.isnull().sum()

EMPLOYEE_ID        0
FIRST_NAME         0
LAST_NAME          0
PHONE_NUMBER       0
HIRE_DATE          0
JOB_ID             0
SALARY             0
COMMISSION_PCT    76
MANAGER_ID         1
DEPARTMENT_ID      1
dtype: int64

In [12]:
# commission percentage
com_mean = df['COMMISSION_PCT'].mean()
com_median = df['COMMISSION_PCT'].median()

format_mean = f'{com_mean:,.2f}'
format_mean = float(format_mean)

print(com_mean)
print(format_mean)
print(com_median)

0.22285714285714284
0.22
0.2

In [13]:
type(format_mean)

float

In [14]:
df['COMMISSION_PCT'].skew()

np.float64(0.09661736135041571)

In [15]:
df['COMMISSON_PCT'] = df['COMMISSION_PCT'].fillna(com_mean)
# df['COMMISSION_PCT].fillna(com_mean, inplace = True)
# df.fillna({'COMMISSION_PCT': com_mean}, inplace = True)
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,COMMISSON_PCT
0,100,Steven,King,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0,0.222857
1,101,Neena,Kochhar,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0,0.222857
2,102,Lex,De Haan,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0,0.222857
3,103,Alexander,Hunold,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0,0.222857
4,104,Bruce,Ernst,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0,0.222857

In [16]:
df.drop(columns = 'COMMISSION_PCT')
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,COMMISSON_PCT
0,100,Steven,King,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0,0.222857
1,101,Neena,Kochhar,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0,0.222857
2,102,Lex,De Haan,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0,0.222857
3,103,Alexander,Hunold,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0,0.222857
4,104,Bruce,Ernst,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0,0.222857

In [17]:
mgr_mode = df['MANAGER_ID'].mode()[0]
dep_mode = df['DEPARTMENT_ID'].mode()[0]

In [18]:
print(mgr_mode)

100.0

In [19]:
print(dep_mode)

50.0

In [20]:
df.fillna({'MANAGER_ID' : mgr_mode}, inplace = True)
df.fillna({'DEPARTMENT_ID' : dep_mode}, inplace = True)

In [21]:
df.isnull().sum()

EMPLOYEE_ID        0
FIRST_NAME         0
LAST_NAME          0
PHONE_NUMBER       0
HIRE_DATE          0
JOB_ID             0
SALARY             0
COMMISSION_PCT    76
MANAGER_ID         0
DEPARTMENT_ID      0
COMMISSON_PCT      0
dtype: int64

In [22]:
df['MANAGER_ID'].unique()

array([100., 102., 103., 101., 108., 114., 120., 121., 122., 123., 124.,
       145., 146., 147., 148., 149., 201., 205.])

In [23]:
df['DEPARTMENT_ID'].unique()

array([ 90.,  60., 100.,  30.,  50.,  80.,  10.,  20.,  40.,  70., 110.])

In [24]:
df.fillna({'MANAGER_ID': 0}, inplace = True)
df.fillna({'DEPARTMENT_ID' : 0}, inplace = True)
df['DEPARTMENT_ID'].unique()

array([ 90.,  60., 100.,  30.,  50.,  80.,  10.,  20.,  40.,  70., 110.])

In [25]:
fraud = pd.read_csv('Dataset/Fraud Detection Dataset.csv')
fraud.head()

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Time_of_Transaction,Device_Used,Location,Previous_Fraudulent_Transactions,Account_Age,Number_of_Transactions_Last_24H,Payment_Method,Fraudulent
0,T1,4174,1292.76,ATM Withdrawal,16.0,Tablet,San Francisco,0,119,13,Debit Card,0
1,T2,4507,1554.58,ATM Withdrawal,13.0,Mobile,New York,4,79,3,Credit Card,0
2,T3,1860,2395.02,ATM Withdrawal,NaN,Mobile,NaN,3,115,9,NaN,0
3,T4,2294,100.10,Bill Payment,15.0,Desktop,Chicago,4,3,4,UPI,0
4,T5,2130,1490.50,POS Payment,19.0,Mobile,San Francisco,2,57,7,Credit Card,0

In [26]:
fraud.isnull().sum()

Transaction_ID                         0
User_ID                                0
Transaction_Amount                  2520
Transaction_Type                       0
Time_of_Transaction                 2552
Device_Used                         2473
Location                            2547
Previous_Fraudulent_Transactions       0
Account_Age                            0
Number_of_Transactions_Last_24H        0
Payment_Method                      2469
Fraudulent                             0
dtype: int64

In [27]:
fraud.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51000 entries, 0 to 50999
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Transaction_ID                    51000 non-null  object
 1   User_ID                           51000 non-null  int64
 2   Transaction_Amount                48480 non-null  float64
 3   Transaction_Type                  51000 non-null  object
 4   Time_of_Transaction               48448 non-null  float64
 5   Device_Used                       48527 non-null  object
 6   Location                          48453 non-null  object
 7   Previous_Fraudulent_Transactions  51000 non-null  int64
 8   Account_Age                       51000 non-null  int64
 9   Number_of_Transactions_Last_24H   51000 non-null  int64
 10  Payment_Method                    48531 non-null  object
 11  Fraudulent                        51000 non-null  int64
dtypes: float64(2), int64(5), object(5)
memory usage: 4.7+ MB

## find duplicate data

In [28]:
duplicate_data = fraud[fraud.duplicated(subset = 'Transaction_ID')]
duplicate_data

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Time_of_Transaction,Device_Used,Location,Previous_Fraudulent_Transactions,Account_Age,Number_of_Transactions_Last_24H,Payment_Method,Fraudulent
50000,T33554,2669,2425.71,Bank Transfer,14.0,Tablet,Seattle,2,40,7,UPI,0
50001,T9428,1001,2448.53,Bank Transfer,19.0,Mobile,San Francisco,4,7,3,NaN,0
50002,T200,3790,4429.89,ATM Withdrawal,17.0,NaN,Miami,1,39,6,UPI,1
50003,T12448,1743,108.00,ATM Withdrawal,15.0,Tablet,Los Angeles,3,67,9,Credit Card,0
50004,T39490,4329,2320.30,ATM Withdrawal,4.0,Desktop,Los Angeles,3,12,10,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...
50995,T33982,2339,3112.51,Bill Payment,15.0,Mobile,New York,0,7,8,Debit Card,0
50996,T31261,2152,2897.15,Online Purchase,3.0,Mobile,Miami,1,75,11,Net Banking,1
50997,T12293,3345,2204.43,POS Payment,18.0,Mobile,San Francisco,3,73,5,Credit Card,0
50998,T42287,1518,4787.17,POS Payment,19.0,Tablet,New York,2,108,14,Net Banking,0
50999,T13665,2315,814.72,POS Payment,3.0,Tablet,Los Angeles,0,50,10,Invalid Method,0

In [29]:
# transaction_id = input("Enter you txn id: ")
# data = fraud[fraud['Transaction_ID'] == transaction_id]
# data.head(2)

In [30]:
fraud = fraud.drop_duplicates(subset = 'Transaction_ID', keep = 'first')
fraud[fraud.duplicated()]

Empty DataFrame
Columns: [Transaction_ID, User_ID, Transaction_Amount, Transaction_Type, Time_of_Transaction, Device_Used, Location, Previous_Fraudulent_Transactions, Account_Age, Number_of_Transactions_Last_24H, Payment_Method, Fraudulent]
Index: []

In [31]:
## to remove unwanted space and records
# strip(), lstrip(), rstrip()
# replace(find,replace_value) - for digits and characters
# replace(find, replace_value, regex = False) - for regular expressions

In [32]:
hr = pd.read_csv('Dataset/HR_Dataset Refresh.csv')
hr.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

In [33]:
hr.isnull().sum()

Employee_Name                   0
EmpID                           0
MarriedID                       0
MaritalStatusID                 0
GenderID                        0
EmpStatusID                     0
DeptID                          0
PerfScoreID                     0
FromDiversityJobFairID          0
Salary                          0
Termd                           0
PositionID                      0
Position                        0
State                           0
Zip                             0
DOB                             0
Gender                          0
MaritalDesc                     0
CitizenDesc                     0
HispanicLatino                  0
RaceDesc                        0
DateofHire                      0
DateofTermination             386
TermReason                      0
EmploymentStatus                0
Department                      0
ManagerName                     0
ManagerID                       8
RecruitmentSource               0
PerformanceScore                0
EngagementSurvey                0
EmpSatisfaction                 0
SpecialProjectsCount            0
LastPerformanceReview_Date      0
DaysLateLast30                  0
Absences                        0
dtype: int64

In [34]:
mgr_mode = hr['ManagerID'].mode()[0]
mgr_mode

np.float64(16.0)

In [35]:
hr.fillna({'ManagerID' : mgr_mode}, inplace = True)

In [36]:
duplicated_data = hr[hr.duplicated(subset = 'EmpID')]
duplicated_data

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
19,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
20,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
21,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
22,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
23,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
578,"Anderson, Linda",10002,0,0,0,1,5,4,0,57568,...,Amy Dunn,11.0,LinkedIn,Exceeds,5.00,5,0,1/7/2019,0,15
579,"Andreola, Colby",10194,0,0,0,1,4,3,0,95660,...,Alex Sweetwater,10.0,LinkedIn,Fully Meets,3.04,3,4,1/2/2019,0,19
580,"Athwal, Sam",10062,0,4,1,1,5,3,0,59365,...,Ketsia Liebig,19.0,Employee Referral,Fully Meets,5.00,4,0,2/25/2019,0,19
581,"Bachiochi, Linda",10114,0,0,0,3,5,3,1,47837,...,Brannon Miller,12.0,Diversity Job Fair,Fully Meets,4.46,3,0,1/25/2019,0,4

In [37]:
hr = hr.drop_duplicates(subset='EmpID', keep = 'first')
hr

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,"Woodson, Jason",10135,0,0,1,1,5,3,0,65893,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,4.07,4,0,2/28/2019,0,13
326,"Ybarra, Catherine",10301,0,0,0,5,5,1,0,48513,...,Brannon Miller,12.0,Google Search,PIP,3.20,2,0,9/2/2015,5,4
327,"Zamora, Jennifer",10010,0,0,0,1,3,4,0,220450,...,Janet King,2.0,Employee Referral,Exceeds,4.60,5,6,2/21/2019,0,16
328,"Zhou, Julia",10043,0,0,0,1,3,3,0,89292,...,Simon Roup,4.0,Employee Referral,Fully Meets,5.00,3,5,2/1/2019,0,11
329,"Zima, Colleen",10271,0,4,0,1,5,3,0,45046,...,David Stanley,14.0,LinkedIn,Fully Meets,4.50,5,0,1/30/2019,0,2

# removing whitespaces

In [38]:
hr['Department'].unique()

array(['Production       ', 'IT/IS', 'Software Engineering',
       'Admin Offices', 'Sales', 'Executive Office'], dtype=object)

In [39]:
object_columns = hr.select_dtypes(['object','int64'])
object_columns

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,EmploymentStatus,Department,ManagerName,RecruitmentSource,PerformanceScore,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Active,Production,Michael Albert,LinkedIn,Exceeds,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Voluntarily Terminated,IT/IS,Simon Roup,Indeed,Fully Meets,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Voluntarily Terminated,Production,Kissy Sullivan,LinkedIn,Fully Meets,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Active,Production,Elijiah Gray,Indeed,Fully Meets,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Voluntarily Terminated,Production,Webster Butler,Google Search,Fully Meets,4,0,2/1/2016,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,"Woodson, Jason",10135,0,0,1,1,5,3,0,65893,...,Active,Production,Kissy Sullivan,LinkedIn,Fully Meets,4,0,2/28/2019,0,13
326,"Ybarra, Catherine",10301,0,0,0,5,5,1,0,48513,...,Voluntarily Terminated,Production,Brannon Miller,Google Search,PIP,2,0,9/2/2015,5,4
327,"Zamora, Jennifer",10010,0,0,0,1,3,4,0,220450,...,Active,IT/IS,Janet King,Employee Referral,Exceeds,5,6,2/21/2019,0,16
328,"Zhou, Julia",10043,0,0,0,1,3,3,0,89292,...,Active,IT/IS,Simon Roup,Employee Referral,Fully Meets,3,5,2/1/2019,0,11
329,"Zima, Colleen",10271,0,4,0,1,5,3,0,45046,...,Active,Production,David Stanley,LinkedIn,Fully Meets,5,0,1/30/2019,0,2

In [40]:
object_columns.info()

<class 'pandas.core.frame.DataFrame'>
Index: 311 entries, 0 to 329
Data columns (total 34 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               311 non-null    object
 1   EmpID                       311 non-null    int64
 2   MarriedID                   311 non-null    int64
 3   MaritalStatusID             311 non-null    int64
 4   GenderID                    311 non-null    int64
 5   EmpStatusID                 311 non-null    int64
 6   DeptID                      311 non-null    int64
 7   PerfScoreID                 311 non-null    int64
 8   FromDiversityJobFairID      311 non-null    int64
 9   Salary                      311 non-null    int64
 10  Termd                       311 non-null    int64
 11  PositionID                  311 non-null    int64
 12  Position                    311 non-null    object
 13  State                       311 non-null    object
 14  Zip                         311 non-null    int64
 15  DOB                         311 non-null    object
 16  Gender                      311 non-null    object
 17  MaritalDesc                 311 non-null    object
 18  CitizenDesc                 311 non-null    object
 19  HispanicLatino              311 non-null    object
 20  RaceDesc                    311 non-null    object
 21  DateofHire                  311 non-null    object
 22  DateofTermination           104 non-null    object
 23  TermReason                  311 non-null    object
 24  EmploymentStatus            311 non-null    object
 25  Department                  311 non-null    object
 26  ManagerName                 311 non-null    object
 27  RecruitmentSource           311 non-null    object
 28  PerformanceScore            311 non-null    object
 29  EmpSatisfaction             311 non-null    int64
 30  SpecialProjectsCount        311 non-null    int64
 31  LastPerformanceReview_Date  311 non-null    object
 32  DaysLateLast30              311 non-null    int64
 33  Absences                    311 non-null    int64
dtypes: int64(16), object(18)
memory usage: 85.0+ KB

In [41]:
hr['ManagerID'] = hr['ManagerID'].astype(int)
hr['ManagerID'].dtype

# astype change int, str, float, boolean, complex, none

dtype('int64')

In [42]:
# to convert object into datetime data type
# to_datetimem(column_name, format) 
# -- yyyy-mm-dd (what type of date format is in my dataset)
'''
    format:
        1. '%d.%m.%y
        2. '%d/%m/%y
        3. 'mixed'

        dayfirst = True/False(default)
'''

"\n    format:\n        1. '%d.%m.%y\n        2. '%d/%m/%y\n        3. 'mixed'\n\n        dayfirst = True/False(default)\n"

In [43]:
print(hr['DOB'].dtype)
hr['DOB'].head(2)

object

0    7/10/1983
1     5/5/1975
Name: DOB, dtype: object

In [44]:
hr['DOB'] = pd.to_datetime(hr['DOB'], format='mixed')
hr.head(2)

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17

In [45]:
def convertDateTime(dataframe, *args):
    for col in args:
        dataframe[col] = pd.to_datetime(dataframe[col], format = 'mixed')

convertDateTime(hr,'DOB', 'LastPerformanceReview_Date')

In [46]:
object_columns.columns
columns = ['Employee_Name', 'EmpID', 'MarriedID', 'MaritalStatusID', 'GenderID',
       'EmpStatusID', 'DeptID', 'PerfScoreID', 'FromDiversityJobFairID',
       'Salary', 'Termd', 'PositionID', 'Position', 'State', 'Zip', 'DOB',
       'Gender', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino', 'RaceDesc',
       'DateofHire', 'DateofTermination', 'TermReason', 'EmploymentStatus',
       'Department', 'ManagerName', 'RecruitmentSource', 'PerformanceScore',
       'EmpSatisfaction', 'SpecialProjectsCount', 'LastPerformanceReview_Date',
       'DaysLateLast30', 'Absences']

In [47]:
def finduniquevalues(dataframe, columns):
    for col in columns:
        print(col)
        print('-'*55)
        unique_values = dataframe[col].unique()
        print(unique_values)
        print('\n')

finduniquevalues(hr,columns)

Employee_Name
-------------------------------------------------------
['Adinolfi, Wilson  K' 'Ait Sidi, Karthikeyan   ' 'Akinkuolie, Sarah'
 'Alagbe,Trina' 'Anderson, Carol ' 'Anderson, Linda  ' 'Andreola, Colby'
 'Athwal, Sam' 'Bachiochi, Linda' 'Bacong, Alejandro '
 'Baczenski, Rachael  ' 'Barbara, Thomas' 'Barbossa, Hector'
 'Barone, Francesco  A' 'Barton, Nader' 'Bates, Norman' 'Beak, Kimberly  '
 'Beatrice, Courtney ' 'Becker, Renee' 'Becker, Scott' 'Bernstein, Sean'
 'Biden, Lowan  M' 'Billis, Helen' 'Blount, Dianna' 'Bondwell, Betsy'
 'Booth, Frank' 'Boutwell, Bonalyn' 'Bozzi, Charles' 'Brill, Donna'
 'Brown, Mia' 'Buccheri, Joseph  ' 'Bugali, Josephine ' 'Bunbury, Jessica'
 'Burke, Joelle' 'Burkett, Benjamin ' 'Cady, Max ' 'Candie, Calvin'
 'Carabbio, Judith' 'Carey, Michael  ' 'Carr, Claudia  N'
 'Carter, Michelle ' 'Chace, Beatrice ' 'Champaigne, Brian' 'Chan, Lin'
 'Chang, Donovan  E' 'Chigurh, Anton' 'Chivukula, Enola'
 'Cierpiszewski, Caroline  ' 'Clayton, Rick' 'Cloninger, Jennifer'
 'Close, Phil' 'Clukey, Elijian' 'Cockel, James' 'Cole, Spencer'
 'Corleone, Michael' 'Corleone, Vito' 'Cornett, Lisa ' 'Costello, Frank'
 'Crimmings,   Jean' 'Cross, Noah' 'Daneault, Lynn' 'Daniele, Ann  '
 "Darson, Jene'ya " 'Davis, Daniel' 'Dee, Randy' 'DeGweck,  James'
 'Del Bosque, Keyla' 'Delarge, Alex' 'Demita, Carla' 'Desimone, Carl '
 'DeVito, Tommy' 'Dickinson, Geoff ' 'Dietrich, Jenna  ' 'DiNocco, Lily '
 'Dobrin, Denisa  S' 'Dolan, Linda' 'Dougall, Eric' 'Driver, Elle'
 'Dunn, Amy  ' 'Dunne, Amy' 'Eaton, Marianne' 'Engdahl, Jean'
 'England, Rex' 'Erilus, Angela' 'Estremera, Miguel' 'Evensen, April'
 'Exantus, Susan' 'Faller, Megan ' 'Fancett, Nicole' 'Ferguson, Susan'
 'Fernandes, Nilson  ' 'Fett, Boba' 'Fidelia,  Libby'
 'Fitzpatrick, Michael  J' 'Foreman, Tanya' 'Forrest, Alex' 'Foss, Jason'
 'Foster-Baker, Amy' 'Fraval, Maruk ' 'Galia, Lisa' 'Garcia, Raul'
 'Gaul, Barbara' 'Gentry, Mildred' 'Gerke, Melisa' 'Gill, Whitney  '
 'Gilles, Alex' 'Girifalco, Evelyn' 'Givens, Myriam' 'Goble, Taisha'
 'Goeth, Amon' 'Gold, Shenice  ' 'Gonzalez, Cayo' 'Gonzalez, Juan'
 'Gonzalez, Maria' 'Good, Susan' 'Gordon, David' 'Gosciminski, Phylicia  '
 'Goyal, Roxana' 'Gray, Elijiah  ' 'Gross, Paula' 'Gruber, Hans'
 'Guilianno, Mike' 'Handschiegl, Joanne' 'Hankard, Earnest'
 'Harrington, Christie ' 'Harrison, Kara' 'Heitzman, Anthony'
 'Hendrickson, Trina' 'Hitchcock, Alfred' 'Homberger, Adrienne  J'
 'Horton, Jayne' 'Houlihan, Debra' 'Howard, Estelle' 'Hudson, Jane'
 'Hunts, Julissa' 'Hutter, Rosalie' 'Huynh, Ming' 'Immediato, Walter'
 'Ivey, Rose ' 'Jackson, Maryellen' 'Jacobi, Hannah  ' 'Jeannite, Tayana'
 'Jhaveri, Sneha  ' 'Johnson, George' 'Johnson, Noelle ' 'Johnston, Yen'
 'Jung, Judy  ' 'Kampew, Donysha' 'Keatts, Kramer '
 'Khemmich, Bartholemew' 'King, Janet' 'Kinsella, Kathleen  '
 'Kirill, Alexandra  ' 'Knapp, Bradley  J' 'Kretschmer, John'
 'Kreuger, Freddy' 'Lajiri,  Jyoti' 'Landa, Hans' 'Langford, Lindsey'
 'Langton, Enrico' 'LaRotonda, William  ' 'Latif, Mohammed' 'Le, Binh'
 'Leach, Dallas' 'LeBlanc, Brandon  R' 'Lecter, Hannibal'
 'Leruth, Giovanni' 'Liebig, Ketsia' 'Linares, Marilyn ' 'Linden, Mathew'
 'Lindsay, Leonara ' 'Lundy, Susan' 'Lunquist, Lisa' 'Lydon, Allison'
 'Lynch, Lindsay' 'MacLennan, Samuel' 'Mahoney, Lauren  '
 'Manchester, Robyn' 'Mancuso, Karen' 'Mangal, Debbie' 'Martin, Sandra'
 'Maurice, Shana' "Carthy, B'rigit" 'Mckenna, Sandy' 'McKinzie, Jac'
 'Meads, Elizabeth' 'Medeiros, Jennifer' 'Miller, Brannon' 'Miller, Ned'
 'Monkfish, Erasumus' 'Monroe, Peter' 'Monterro, Luisa' 'Moran, Patrick'
 'Morway, Tanya' 'Motlagh,  Dawn' 'Moumanil, Maliki ' 'Myers, Michael'
 'Navathe, Kurt' 'Ndzi, Colombui' 'Ndzi, Horia' 'Newman, Richard '
 'Ngodup, Shari ' 'Nguyen, Dheepa' 'Nguyen, Lei-Ming' 'Nowlan, Kristie'
 "O'hare, Lynn" 'Oliver, Brooke ' 'Onque, Jasmine' 'Osturnka, Adeel'
 'Owad, Clinton' 'Ozark, Travis' 'Panjwani, Nina' 'Patronick, Lucas'
 'Pearson, Randall' 'Smith, Martin' 'Pelletier, Ermine' 'Perry, Shakira'
 'Peters, Lauren' 'Peterson, Ebonee  ' 'Petingill, Shana  '
 'Petrowsky, Thelma' 'Pham, Hong' 'Pitt, Brad ' 'Potts, Xana'
 'Power, Morissa' 'Punjabhi, Louis  ' 'Purinton, Janine' 'Quinn, Sean'
 'Rachael, Maggie' 'Rarrick, Quinn' 'Ren, Kylo' 'Rhoads, Thomas'
 'Rivera, Haley  ' 'Roberson, May' 'Robertson, Peter' 'Robinson, Alain  '
 'Robinson, Cherly' 'Robinson, Elias' 'Roby, Lori ' 'Roehrich, Bianca'
 'Roper, Katie' 'Rose, Ashley  ' 'Rossetti, Bruno' 'Roup,Simon'
 'Ruiz, Ricardo' 'Saada, Adell' 'Saar-Beckles, Melinda' 'Sadki, Nore  '
 'Sahoo, Adil' 'Salter, Jason' 'Sander, Kamrin' 'Sewkumar, Nori'
 'Shepard, Anita ' 'Shields, Seffi' 'Simard, Kramer' 'Singh, Nan '
 'Sloan, Constance' 'Smith, Joe' 'Smith, John' 'Smith, Leigh Ann'
 'Smith, Sade' 'Soto, Julia ' 'Soze, Keyser' 'Sparks, Taylor  '
 'Spirea, Kelley' 'Squatrito, Kristen' 'Stanford,Barbara  M'
 'Stansfield, Norman' 'Steans, Tyrone  ' 'Stoica, Rick' 'Strong, Caitrin'
 'Sullivan, Kissy ' 'Sullivan, Timothy' 'Sutwell, Barbara' 'Szabo, Andrew'
 'Tannen, Biff' 'Tavares, Desiree  ' 'Tejeda, Lenora ' 'Terry, Sharlene '
 'Theamstern, Sophia' 'Thibaud, Kenneth' 'Tippett, Jeanette'
 'Torrence, Jack' 'Trang, Mei' 'Tredinnick, Neville ' 'True, Edward'
 'Trzeciak, Cybil' 'Turpin, Jumil' 'Valentin,Jackie' 'Veera, Abdellah '
 'Vega, Vincent' 'Villanueva, Noah' 'Voldemort, Lord' 'Volk, Colleen'
 'Von Massenbach, Anna' 'Walker, Roger' 'Wallace, Courtney  E'
 'Wallace, Theresa' 'Wang, Charlie' 'Warfield, Sarah' 'Whittier, Scott'
 'Wilber, Barry' 'Wilkes, Annie' 'Williams, Jacquelyn  '
 'Winthrop, Jordan  ' 'Wolk, Hang  T' 'Woodson, Jason'
 'Ybarra, Catherine ' 'Zamora, Jennifer' 'Zhou, Julia' 'Zima, Colleen']


EmpID
-------------------------------------------------------
[10026 10084 10196 10088 10069 10002 10194 10062 10114 10250 10252 10242
 10012 10265 10066 10061 10023 10055 10245 10277 10046 10226 10003 10294
 10267 10199 10081 10175 10177 10238 10184 10203 10188 10107 10181 10150
 10001 10085 10115 10082 10040 10067 10108 10210 10154 10200 10240 10168
 10220 10275 10269 10029 10261 10292 10282 10019 10094 10193 10132 10083
 10099 10212 10056 10143 10311 10070 10155 10306 10100 10310 10197 10276
 10304 10284 10207 10133 10028 10006 10105 10211 10064 10247 10235 10299
 10280 10296 10290 10263 10136 10189 10308 10309 10049 10093 10163 10305
 10015 10080 10258 10273 10111 10257 10159 10122 10142 10283 10018 10255
 10246 10228 10243 10031 10300 10101 10237 10051 10218 10256 10098 10059
 10234 10109 10125 10074 10097 10007 10129 10075 10167 10195 10112 10272
 10182 10248 10201 10214 10160 10289 10139 10227 10236 10009 10060 10034
 10156 10036 10138 10244 10192 10231 10089 10166 10170 10208 10176 10165
 10113 10092 10106 10052 10038 10249 10232 10087 10134 10251 10103 10017
 10186 10137 10008 10096 10035 10057 10004 10191 10219 10077 10073 10279
 10110 10053 10076 10145 10202 10128 10068 10116 10298 10213 10288 10025
 10223 10151 10254 10120 10216 10079 10215 10185 10063 10037 10042 10206
 10104 10303 10078 10121 10021 10281 10041 10148 10005 10259 10286 10297
 10171 10032 10130 10217 10016 10050 10164 10124 10187 10225 10262 10131
 10239 10152 10140 10058 10011 10230 10224 10047 10285 10020 10162 10149
 10086 10054 10065 10198 10222 10126 10295 10260 10233 10229 10169 10071
 10179 10091 10178 10039 10095 10027 10291 10153 10157 10119 10180 10302
 10090 10030 10278 10307 10147 10266 10241 10158 10117 10209 10024 10173
 10221 10146 10161 10141 10268 10123 10013 10287 10044 10102 10270 10045
 10205 10014 10144 10253 10118 10022 10183 10190 10274 10293 10172 10127
 10072 10048 10204 10264 10033 10174 10135 10301 10010 10043 10271]


MarriedID
-------------------------------------------------------
[0 1]


MaritalStatusID
-------------------------------------------------------
[0 1 2 4 3]


GenderID
-------------------------------------------------------
[1 0]


EmpStatusID
-------------------------------------------------------
[1 5 3 4 2]


DeptID
-------------------------------------------------------
[5 3 4 1 6 2]


PerfScoreID
-------------------------------------------------------
[4 3 2 1]


FromDiversityJobFairID
-------------------------------------------------------
[0 1]


Salary
-------------------------------------------------------
[ 62506 104437  64955  64991  50825  57568  95660  59365  47837  50178
  54670  47211  92328  58709  52505  57834  70131  59026 110000  53250
  51044  64919  62910  66441  57815 103613 106367  74312  53492  63000
  65288  64375  74326  63763  62162  77692  72640  93396  52846 100031
  71860  61656 110929  54237  60380  66808  64786  64816  68678  64066
  59369  50373  63108  59144  68051 170500  63381  83552  56149  92329
  65729  85028  57583  56294  56991  55722 101199  61568  58275  53189
  96820  51259  59231  61584  46335  70621 138888  74241  75188  62514
  60070  48888  54285  56847  60340  59124  99280  71776  65902  57748
  64057  53366  58530  72609  55965  70187 178000  99351  67251  65707
  52249  53171  51337  51505  59370  54933  61555 114800  74679  53018
  59892  68898  61242  66825  48285  66149  49256  62957  63813  99020
  71707  54828  64246  52177  62065  46998  68099  70545  63478  97999
 180000  49920  55425  69340  64995  68182  83082  51908  45069  60724
  60436  46837 105700  63322  61154  68999  50482  65310 250000  54005
  45433  46654  63973  71339  93206  82758  66074  46120  64520  61962
  81584  63676  93046  64738  70468  77915  52624  63450  51777  67237
  73330  52057  47434  52788  45395  62385  68407  61349 105688  54132
  55315  62810  63291  62659  55688  83667  55800  58207 157000  72460
  72106  52599  63430  74417  57575  87921  50470  46664  48495  52984
  63695  62061  66738  52674  71966  63051  47414  53060  68829  63515
 108987  93093  53564  60270  45998  57954  74669  74226  93554  64724
  47001  61844  46799  59472  46430  83363  95920  61729  61809  45115
  46738  64971  55578  50428  61422  63353  89883 120000 150290  60627
  53180 140920 148999  86214  47750  46428  57975  88527  56147  50923
  50750  52087  87826  51920  63878  60656  72992  55000  58939  66593
  87565  64021  65714  62425  47961  58273  63003  61355  60120  63682
  63025  59238  92989  90100  60754  72202  58370  48413  67176  56339
  64397  75281 100416  74813  76029  57859  58523  88976  55875 113999
  49773  62068  66541  80512  50274  84903 107226  58371  55140  58062
  59728  70507  60446  65893  48513 220450  89292  45046]


Termd
-------------------------------------------------------
[0 1]


PositionID
-------------------------------------------------------
[19 27 20 24 14  9  8 30 26 18  1  3 25  5 10 28 21  4 13 15 12 11  2 16
 22 23 29  7 17  6]


Position
-------------------------------------------------------
['Production Technician I' 'Sr. DBA' 'Production Technician II'
 'Software Engineer' 'IT Support' 'Data Analyst' 'Database Administrator'
 'Enterprise Architect' 'Sr. Accountant' 'Production Manager'
 'Accountant I' 'Area Sales Manager' 'Software Engineering Manager'
 'BI Director' 'Director of Operations' 'Sr. Network Engineer'
 'Sales Manager' 'BI Developer' 'IT Manager - Support' 'Network Engineer'
 'IT Director' 'Director of Sales' 'Administrative Assistant'
 'President & CEO' 'Senior BI Developer' 'Shared Services Manager'
 'IT Manager - Infra' 'Principal Data Architect' 'Data Architect'
 'IT Manager - DB' 'Data Analyst ' 'CIO']


State
-------------------------------------------------------
['MA' 'TX' 'CT' 'VA' 'VT' 'AL' 'WA' 'CA' 'OH' 'IN' 'TN' 'NH' 'RI' 'PA'
 'CO' 'NY' 'UT' 'GA' 'FL' 'NC' 'KY' 'ID' 'NV' 'MT' 'OR' 'ND' 'AZ' 'ME']


Zip
-------------------------------------------------------
[ 1960  2148  1810  1886  2169  1844  2110  2199  1902  2062 78230  2747
  2050  2145  1915  2026  2452  2072  2027  2031  2171  2210  6033  2468
  1901  1701  1450  1013  2043 21851  1890  2184  2132  5664  2763  2045
  2170  1845 78207  1775  2044  1752  2134  1880  1803  2030  2189  1821
  6278  5473  2458  2138  2176 36006  2343  2061  2180 98052  2351  2125
  2119 90007  1731  1749  2133  2129  1824  2324  2155  2143  2330  1460
  6050  6040  1905  2121 43050  2451 46204  2127  2135  2108  2128  2472
  1864 37129  2149  2021  3062  2445  2493  2908  1742  2081  1778  2109
  2301  2446 19444  1887 80820  1721  1801 10171  2090  2048  2126  1776
 84111  1770  6070  2122  1938 78789  1760  2346  2453  1550  2056  2421
  2136 30428  1040  2152  2492 33174  2478 27229 40220  2474 83706  1420
  1730  2703  2481  2154  2191  1773  1851  2130  2360  1545  2093  2359
 89139 59102  2718  2140 97756  2066 58782 85006  4063  2124  2459  1876
  2302  2067]


DOB
-------------------------------------------------------
<DatetimeArray>
['1983-07-10 00:00:00', '1975-05-05 00:00:00', '1988-09-19 00:00:00',
 '1988-09-27 00:00:00', '1989-09-08 00:00:00', '1977-05-22 00:00:00',
 '1979-05-24 00:00:00', '1983-02-18 00:00:00', '1970-02-11 00:00:00',
 '1988-01-07 00:00:00',
 ...
 '1987-05-24 00:00:00', '1983-07-30 00:00:00', '1969-10-02 00:00:00',
 '1958-11-07 00:00:00', '1985-04-20 00:00:00', '1985-05-11 00:00:00',
 '1982-05-04 00:00:00', '1979-08-30 00:00:00', '1979-02-24 00:00:00',
 '1978-08-17 00:00:00']
Length: 307, dtype: datetime64[ns]


Gender
-------------------------------------------------------
['M ' 'F']


MaritalDesc
-------------------------------------------------------
['Single' 'Married' 'Divorced' 'Widowed' 'Separated']


CitizenDesc
-------------------------------------------------------
['US Citizen' 'Eligible NonCitizen' 'Non-Citizen']


HispanicLatino
-------------------------------------------------------
['No' 'Yes' 'no' 'yes']


RaceDesc
-------------------------------------------------------
['White' 'Black or African American' 'Two or more races' 'Asian'
 'American Indian or Alaska Native' 'Hispanic']


DateofHire
-------------------------------------------------------
['7/5/2011' '3/30/2015' '1/7/2008' '7/11/2011' '1/9/2012' '11/10/2014'
 '9/30/2013' '7/6/2009' '1/5/2015' '1/10/2011' '4/2/2012' '2/20/2012'
 '9/24/2012' '2/21/2011' '7/21/2016' '4/4/2011' '7/7/2014' '7/8/2013'
 '8/19/2013' '2/17/2014' '2/16/2015' '10/27/2008' '9/29/2014' '11/11/2013'
 '8/15/2011' '3/5/2012' '1/28/2016' '3/31/2014' '6/30/2016' '8/18/2014'
 '9/6/2016' '5/12/2014' '5/14/2012' '6/27/2011' '10/3/2011' '9/5/2012'
 '5/16/2011' '8/30/2010' '7/6/2016' '7/20/2010' '1/5/2009' '5/5/2014'
 '7/2/2012' '11/7/2011' '7/9/2018' '2/15/2017' '1/7/2013' '1/5/2014'
 '9/18/2014' '4/26/2010' '5/2/2011' '5/11/2015' '4/15/2011' '9/6/2011'
 '5/1/2010' '6/2/2015' '4/20/2017' '3/7/2012' '11/28/2011' '8/13/2012'
 '6/6/2016' '6/5/2015' '11/5/2012' '1/6/2014' '9/26/2011' '3/7/2011'
 '7/9/2012' '10/2/2016' '1/5/2016' '4/30/2012' '1/21/2011' '5/11/2016'
 '5/31/2011' '8/16/2012' '2/15/2012' '5/13/2013' '4/1/2013' '2/10/2017'
 '2/7/2011' '12/1/2014' '10/25/2010' '11/5/2007' '1/7/2017' '1/20/2013'
 '7/4/2016' '9/30/2014' '5/1/2015' '10/26/2009' '5/18/2014' '6/10/2011'
 '10/2/2012' '9/27/2010' '1/8/2009' '4/27/2009' '6/25/2007' '2/18/2013'
 '1/9/2006' '8/1/2011' '7/5/2015' '9/2/2008' '4/10/2010']


DateofTermination
-------------------------------------------------------
[nan '6/16/2016' '9/24/2012' '9/6/2016' '1/12/2017' '9/19/2016' '4/6/2017'
 '8/4/2017' '9/12/2015' '4/4/2014' '2/19/2016' '8/7/2014' '6/15/2013'
 '8/2/2014' '11/15/2015' '1/7/2013' '9/26/2011' '9/23/2016' '6/8/2016'
 '11/4/2015' '6/6/2017' '9/27/2018' '2/25/2018' '6/5/2013' '5/17/2016'
 '6/24/2013' '1/9/2013' '8/19/2018' '11/15/2016' '9/5/2015' '6/25/2015'
 '3/15/2015' '5/30/2011' '1/11/2014' '10/31/2014' '12/15/2015' '6/18/2013'
 '4/7/2012' '4/15/2015' '4/1/2013' '4/29/2018' '4/1/2016' '4/24/2014'
 '6/4/2015' '1/9/2014' '12/12/2015' '3/31/2014' '4/15/2013' '9/26/2018'
 '9/15/2016' '11/14/2015' '9/26/2017' '8/19/2012' '11/11/2016' '9/4/2014'
 '5/25/2016' '5/1/2018' '8/19/2013' '1/12/2014' '9/7/2015' '5/1/2016'
 '12/28/2017' '9/15/2015' '10/25/2015' '2/4/2013' '5/18/2016' '11/30/2012'
 '6/4/2018' '8/15/2015' '4/7/2018' '1/15/2016' '10/22/2011' '2/8/2012'
 '1/26/2016' '11/10/2018' '8/13/2018' '7/30/2018' '10/31/2015' '4/8/2015'
 '9/25/2013' '6/29/2015' '7/8/2017' '9/5/2016' '8/30/2010' '2/12/2016'
 '4/15/2018' '7/2/2014' '2/5/2016' '2/22/2017' '2/8/2016' '1/2/2012'
 '9/1/2015' '5/15/2014' '5/14/2012' '6/27/2015' '2/21/2016' '9/29/2015']


TermReason
-------------------------------------------------------
['N/A-StillEmployed' 'career change' 'hours' 'return to school'
 'Another position' 'unhappy' 'attendance' 'performance'
 'Learned that he is a gangster' 'retiring' 'relocation out of area'
 'more money' 'military' 'no-call, no-show' 'Fatal attraction'
 'maternity leave - did not return' 'medical issues' 'gross misconduct']


EmploymentStatus
-------------------------------------------------------
['Active' 'Voluntarily Terminated' 'Terminated for Cause']


Department
-------------------------------------------------------
['Production       ' 'IT/IS' 'Software Engineering' 'Admin Offices'
 'Sales' 'Executive Office']


ManagerName
-------------------------------------------------------
['Michael Albert' 'Simon Roup' 'Kissy Sullivan' 'Elijiah Gray'
 'Webster Butler' 'Amy Dunn' 'Alex Sweetwater' 'Ketsia Liebig'
 'Brannon Miller' 'Peter Monroe' 'David Stanley' 'Kelley Spirea'
 'Brandon R. LeBlanc' 'Janet King' 'John Smith' 'Jennifer Zamora'
 'Lynn Daneault' 'Eric Dougall' 'Debra Houlihan' 'Brian Champaigne'
 'Board of Directors']


RecruitmentSource
-------------------------------------------------------
['LinkedIn' 'Indeed' 'Google Search' 'Employee Referral'
 'Diversity Job Fair' 'On-line Web application' 'CareerBuilder' 'Website'
 'Other']


PerformanceScore
-------------------------------------------------------
['Exceeds' 'Fully Meets' 'Needs Improvement' 'PIP']


EmpSatisfaction
-------------------------------------------------------
[5 3 4 2 1]


SpecialProjectsCount
-------------------------------------------------------
[0 6 4 5 7 3 8 2 1]


LastPerformanceReview_Date
-------------------------------------------------------
<DatetimeArray>
['2019-01-17 00:00:00', '2016-02-24 00:00:00', '2012-05-15 00:00:00',
 '2019-01-03 00:00:00', '2016-02-01 00:00:00', '2019-01-07 00:00:00',
 '2019-01-02 00:00:00', '2019-02-25 00:00:00', '2019-01-25 00:00:00',
 '2019-02-18 00:00:00',
 ...
 '2017-02-15 00:00:00', '2015-02-01 00:00:00', '2012-01-02 00:00:00',
 '2014-09-05 00:00:00', '2019-02-05 00:00:00', '2014-05-15 00:00:00',
 '2011-02-06 00:00:00', '2014-06-02 00:00:00', '2016-01-19 00:00:00',
 '2015-09-02 00:00:00']
Length: 137, dtype: datetime64[ns]


DaysLateLast30
-------------------------------------------------------
[0 2 1 5 3 6 4]


Absences
-------------------------------------------------------
[ 1 17  3 15  2 19  4 16 12  9  7 20  8 13  5 14  6 11 10 18]

In [48]:
hr['Department'] = hr['Department'].str.strip()

In [49]:
def removeWhiteSpace(dataframe, columns):
    for col in columns:
        if dataframe[col].dtype == "object" or str(dataframe[col].dtype) == "string":
            dataframe[col] = dataframe[col].str.strip()
    return dataframe

In [50]:
data = removeWhiteSpace(hr, columns)

In [51]:
data['HispanicLatino'] = data['HispanicLatino'].str.replace('no', 'No')
data['HispanicLatino'] = data['HispanicLatino'].str.capitalize() # convert words first letter to upper case
data['Employee_Name'] = data['Employee_Name'].str.replace(',', ' ', regex=False)

In [52]:
data.to_excel('cleaned_data.xlsx', index = False)

In [53]:
new_data = pd.read_excel('cleaned_data.xlsx')
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311 entries, 0 to 310
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               311 non-null    object
 1   EmpID                       311 non-null    int64
 2   MarriedID                   311 non-null    int64
 3   MaritalStatusID             311 non-null    int64
 4   GenderID                    311 non-null    int64
 5   EmpStatusID                 311 non-null    int64
 6   DeptID                      311 non-null    int64
 7   PerfScoreID                 311 non-null    int64
 8   FromDiversityJobFairID      311 non-null    int64
 9   Salary                      311 non-null    int64
 10  Termd                       311 non-null    int64
 11  PositionID                  311 non-null    int64
 12  Position                    311 non-null    object
 13  State                       311 non-null    object
 14  Zip                         311 non-null    int64
 15  DOB                         311 non-null    datetime64[ns]
 16  Gender                      311 non-null    object
 17  MaritalDesc                 311 non-null    object
 18  CitizenDesc                 311 non-null    object
 19  HispanicLatino              311 non-null    object
 20  RaceDesc                    311 non-null    object
 21  DateofHire                  311 non-null    object
 22  DateofTermination           104 non-null    object
 23  TermReason                  311 non-null    object
 24  EmploymentStatus            311 non-null    object
 25  Department                  311 non-null    object
 26  ManagerName                 311 non-null    object
 27  ManagerID                   311 non-null    int64
 28  RecruitmentSource           311 non-null    object
 29  PerformanceScore            311 non-null    object
 30  EngagementSurvey            311 non-null    float64
 31  EmpSatisfaction             311 non-null    int64
 32  SpecialProjectsCount        311 non-null    int64
 33  LastPerformanceReview_Date  311 non-null    datetime64[ns]
 34  DaysLateLast30              311 non-null    int64
 35  Absences                    311 non-null    int64
dtypes: datetime64[ns](2), float64(1), int64(17), object(16)
memory usage: 87.6+ KB